AppItaqueraParaElas/Models/App.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppItaqueraParaElas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class appEntities : DbContext
    {
        public appEntities()
            : base("name=appEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DADOS_SEGURANCA> DADOS_SEGURANCA { get; set; }
        public virtual DbSet<TRANSPORTE> TRANSPORTE { get; set; }
    }
}

AppItaqueraParaElas/Models/App.Designer.cs
// T4 code generation is enabled for model 'C:\Users\th_r_\source\repos\AppItaqueraParaElas\AppItaqueraParaElas\Models\App.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

AppItaqueraParaElas/Models/App.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

AppItaqueraParaElas/Models/DADOS_SEGURANCA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppItaqueraParaElas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DADOS_SEGURANCA
    {
        public string TIPO { get; set; }
        public string NOME { get; set; }
        public string ENDEREÇO { get; set; }
        public string BAIRRO { get; set; }
        public double LATITUDE { get; set; }
        public double LONGITUDE { get; set; }
        public long ID { get; set; }
        public string REGIAO { get; set; }
    }
}

AppItaqueraParaElas/Models/TRANSPORTE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppItaqueraParaElas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public string TIPO { get; set; }
        public string DESCRICAO { get; set; }
        public string ENDERECO { get; set; }
        public string REGIAO { get; set; }
        public double LATITUDE { get; set; }
        public double LONGITUDE { get; set; }
        public long ID { get; set; }
    }
}

AppItaqueraParaElas/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppItaqueraParaElas.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }
    }
}

AppItaqueraParaElas/Controllers/IndiceSegurancaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AppItaqueraParaElas.Models;

namespace AppItaqueraParaElas.Controllers
{
    public class IndiceSegurancaController : Controller
    {
        
        // GET: IndiceSeguranca
        public ActionResult Index()
        {       
            return View();
        }
    }
}

AppItaqueraParaElas/Controllers/MapaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppItaqueraParaElas.Controllers
{
    public class MapaController : Controller
    {
        // GET: Mapa
        public ActionResult Index()
        {
            return View();
        }
    }
}

AppItaqueraParaElas/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title</h2>
<h3 class="text-center">Ajudamos você a saber as regiões mais seguras ou menos seguras de Itaquera!</h3>

<p class="text-justify">
    Mapeamos as regiões de Itaquera e as classificamos em relação à sua segurança seguindo os seguintes critérios:
    Iluminação pública: Estudos comprovam que vias iluminadas são mais seguras, por isso acreditamos na importância de trazer a luz como um dos nossos medidores.
    Postos policiais: A presença de postos policiais na rua escolhida traz segurança para aquelas que passam por ali.
    Quantidade de pontos transporte público: Quanto maior a proximidade com pontos de ônibus e estações de metrô, maior a movimentação da via e consequentemente a sua segurança.
</p>

AppItaqueraParaElas/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contate-nos";
}
<h2>@ViewBag.Title.</h2>
<h3>Dúvidas? Contate-nos</h3>

<address>
    <strong>Suporte:</strong>   <a href="mailto:alsc8@hotmail.com">Ana L. Coimbra</a><br />
    <strong>        </strong> <a href="mailto:luana.o.marcondes@gmail.com">Luana Marcondes</a><br />
    <strong>        </strong> <a href="mailto:raissa.ricardo@hotmail.com">Raissa Amorim</a><br />
    <strong>        </strong> <a href="mailto:thaisrrey@gmail.com">Thais Rey</a><br />

</address>

AppItaqueraParaElas/Views/Home/Index.cshtml
@{
    ViewBag.Title = "ItaqueraParaElas";
}

<div class="jumbotron">
    <h1>ItaqueraParaElas</h1>
    <p class="lead">Ajudamos você a saber as regiões mais seguras ou menos seguras de Itaquera!</p>
</div>

AppItaqueraParaElas/Views/IndiceSeguranca/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Índice de Segurança</h2>

<div class="jumbotron">
    <h1>Cálculo</h1>
    <p class="lead">I = 40% postos policiais + 30% transporte público + 30% iluminação Pública </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Itaquera</h2>
        <p>
            I=0,56
        </p>
       </div>
    <div class="col-md-4">
        <h2>José Bonifácio</h2>
        <p>
            I=0,3
        </p>
    </div>
    <div class="col-md-4">
        <h2>Parque do Carmo</h2>
        <p>
            I=0,25
        </p>
    </div>
    <div class="col-md-4">
        <h2>Cidade Líder</h2>
        <p>
            I=0,17
        </p>
    </div>
</div>

AppItaqueraParaElas/Views/Mapa/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Localização</h2>

<p>
    <iframe src="//pt.batchgeo.com/map/9107d7739d29287b0e47385147fe7fa2" frameborder="0" width="100%" height="550" style="border:1px solid #aaa;"></iframe>
</p>
<p>
    <small>View <a href="https://pt.batchgeo.com/map/9107d7739d29287b0e47385147fe7fa2">Itaquera Para Elas</a> in a full screen map</small>
</p>

AppItaqueraParaElas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ItaqueraParaElas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Localização", "Index", "Mapa")</li>
                    <li>@Html.ActionLink("Índice de Segurança", "Index", "IndiceSeguranca")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Criado por: Ana L. Coimbra, Luana Marcondes, Raissa Amorim e Thais Rey &copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>